---
name: Upload Test Results
on:
  workflow_dispatch: {}
  schedule:
    # run every hour on the hour
    - cron: 0 * * * *

permissions: read-all

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: "ðŸ§° Checkout Source Code"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests
        run: npm test

      - name: Upload Jest Test Results
        uses: trunk-io/analytics-uploader@main
        # Upload the results even if the tests fail
        if: "!cancelled()"
        with:
          junit-paths: junit.xml
          org-slug: matt
          token: ${{ secrets.TRUNK_API_TOKEN }}
        # don't fail this job if the upload fails
        continue-on-error: true
